on:
     push: 
        branches:
            - main 

jobs :
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }} # your docker hub username and secret token
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: your-dockerhub-username/your-image-name:latest

            - name: Deploy via SSH to EC2
              uses: appleboy/ssh-action@v0.1.0
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER }} # or "ubuntu", depending on your AMI
                port: 22
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                    cd ${{ secrets.EC2_PATH }}
                    docker rm -f container_name || true
                    docker run -d -p 80:80 --name container_name your-dockerhub-username/your-image-name:tag

                    # Restart nginx (in case you're using it as a reverse proxy)
                    sudo systemctl restart nginx


                    
                    

